### PR TITLE
Fix bug with hitsounds

### PR DESCRIPTION
**Pull request by MemeHoovy**
this should fix https://github.com/grafexteam/fnf-grafex/issues/14

### CODE REVIEW

**Review by TheKamboy — CHANGES_REQUESTED** [review]
Maybe you should make an if statement for if ClientPrefs.hsvol is equal to zero, then hitsoundsDisabled can be true.

**Comment by MemeHoovy** [comment]
> Maybe you should make an if statement for if ClientPrefs.hsvol is equal to zero, then hitsoundsDisabled can be true.

ok

**Review by TheKamboy — COMMENTED** [review]
you forgot a round bracket at line 405

**Comment by TheKamboy** [comment]
and also a semi colon.
and this
```
source/grafex/states/playstate/PlayState.hx:396: lines 396-399 : Float should be Bool
source/grafex/states/playstate/PlayState.hx:396: lines 396-399 : ... For function argument 'Function'
```

**Comment by TheKamboy** [comment]
No song will play when I select it.

**Comment by MemeHoovy** [comment]
yeah, this is probably not gonna get merged anyways so...

**Pull request closed without merging**
